#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        #git clone --depth=1 https://github.com/leafsay/rt-n56u.git /opt/rt-n56u
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Set Golang
      run: |
        cd /opt/hostedtoolcache/go
        rm -rf /opt/hostedtoolcache/go/1.14.14
        mv 1.15.8 1.14.14
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
        user_name: admin                       # 用户名
        user_password: xiangyang               # 用户密码
        lan_ip: 192.168.1                      # lan 地址 192.168.1.1 一定别写后面的 .1
        wifi: helloworld                       # wifi密码，切记密码最少8位
        wifi_password: 1234567890              # wifi密码，切记密码最少8位
        version_time: $(date "+%Y%m%d")        # 自动时间更新时版本号: 20200320
        default_path: ./user/shared/defaults.h # 默认文件配置目录
      run: |
        cd /opt/rt-n56u/trunk
        echo '修改用户名'
        sed -i 's/#define\s*SYS_USER_ROOT\s*"admin"/#define SYS_USER_ROOT "'$user_name'"/g' $default_path
        echo '修改密码'
        sed -i 's/#define\s*DEF_ROOT_PASSWORD\s*"admin"/#define DEF_ROOT_PASSWORD "'$user_password'"/g' $default_path
        echo "修改Lan ip"
        sed -i "s/192.168.2/$lan_ip/g" $default_path
        echo "修改Wifi名"
        sed -i 's/#define\s*DEF_WLAN_2G_SSID\s*"_%s"/#define DEF_WLAN_2G_SSID "'$wifi'"/g' $default_path
        sed -i 's/#define\s*DEF_WLAN_5G_SSID\s*"_5G_%s"/#define DEF_WLAN_5G_SSID "'$wifi_5G'"/g' $default_path
        sed -i 's/#define\s*DEF_WLAN_2G_GSSID\s*"_GUEST_%s"/#define DEF_WLAN_2G_GSSID "'$wifi_GUEST'"/g' $default_path
        sed -i 's/#define\s*DEF_WLAN_5G_GSSID\s*"_GUEST_5G_%s"/#define DEF_WLAN_5G_GSSID "'$wifi_GUEST_5G'"/g' $default_path

        echo "修改Wifi密码"
        sed -i "s/1234567890/$wifi_password/g" $default_path
        echo "更新版本号时间"
        sed -i "s/FIRMWARE_BUILDS_REV=[0-9]*/FIRMWARE_BUILDS_REV=$version_time/g" ./versions.inc
        #修改templates
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        #cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' configs/templates/$TNAME.config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_ENABLE_USB/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_UFSD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_FAT/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXFAT/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT2/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT3/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT4/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_XFS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_FUSE/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_ENABLE_SWAP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HID/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SERIAL/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XFRM/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IMQ/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IFB/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPSET/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NFSD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NFSC/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CIFS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NTFS_3G/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LPRD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_U2EC/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HDPARM/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_PARTED/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WINS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD_SYSLOG/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RPL2TP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DDNS_SSL/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTTPS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR_FAST_CODE/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSWAN/d' configs/templates/$TNAME.config
        #sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC/d' configs/templates/$TNAME.config
        #sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIDLNA/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FIREFLY/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' configs/templates/$TNAME.config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' configs/templates/$TNAME.config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' configs/templates/$TNAME.config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> configs/templates/$TNAME.config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=y" >> configs/templates/$TNAME.config #kms
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        cp -f configs/templates/$TNAME.config .config
        cd user
        git init #初始化
        git remote add origin https://github.com/leafsay/rt-n56u.git # 增加远端的仓库地址
        git config core.sparsecheckout true # 设置Sparse Checkout 为true 
        echo "trunk/user/aliddns" >> .git/info/sparse-checkout # 将要部分clone的目录相对根目录的路径写入配置文件
        echo "trunk/user/shadowsocks" >> .git/info/sparse-checkout
        git pull --force --depth 1 origin master
        
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        #sudo ./build_firmware_modify $TNAME 0
        sudo ./build_firmware_modify $TNAME
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
